version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      gomod-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/images/runner"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      docker-runner-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/images/network-adapter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      docker-network-adapter-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/images/network-broker-parser"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      docker-network-broker-parser-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/images/network-broker-dialer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      docker-network-broker-dialer-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/images/network-helper"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      docker-network-helper-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/images/network-verifier"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      docker-network-verifier-minor-patch:
        update-types:
          - "minor"
          - "patch"
